/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by vite-plugin-uni-pages

type _LocationUrl =
  "/pages/index" |
  "/pages/message" |
  "/pages/mine" |
  "/pages/template" |
  "/package-send/conversation-detail" |
  "/package-send/send-record-detail" |
  "/package-send/send-records" |
  "/package-send/send" |
  "/package-template/template-detail" |
  "/package-order/orders" |
  "/package-order/pay" |
  "/package-order/recharge" |
  "/package-feedback/feedback-history" |
  "/package-feedback/feedback" |
  "/package-user/login" |
  "/package-user/settings" |
  "/package-demo/hi";

interface NavigateToOptions {
  url: _LocationUrl;
}
interface RedirectToOptions extends NavigateToOptions {}

interface SwitchTabOptions {
  url: "/pages/index" | "/pages/template" | "/pages/message" | "/pages/mine"
}

type ReLaunchOptions = NavigateToOptions | SwitchTabOptions;

declare interface Uni {
  navigateTo(options: UniNamespace.NavigateToOptions & NavigateToOptions): void;
  redirectTo(options: UniNamespace.RedirectToOptions & RedirectToOptions): void;
  switchTab(options: UniNamespace.SwitchTabOptions & SwitchTabOptions): void;
  reLaunch(options: UniNamespace.ReLaunchOptions & ReLaunchOptions): void;
}

declare module "virtual:uni-pages" {
  export type LocationUrl = _LocationUrl;
}
